language: cpp

os:
  - linux
  - osx
  
sudo: required
dist: trusty
# osx_image: xcode8

branches:
  only:
    - master

compiler:
  - gcc

cache:
  - apt

before_install:
  # dependency installation
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install argp-standalone; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qy update   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qy install automake autoconf libtool ccache gcc g++ libboost-dev libboost-serialization-dev libboost-test-dev libsuitesparse-dev libgsl0-dev libgmp3-dev libxml2-dev doxygen graphviz; fi

script:
  ./configure && make
